### ISSUE TITLE
Donation showing on pricing type as no_price

### ISSUE THREAD

**Issue by responsivesudip** [coinbase/coinbase-commerce-php#12]
I am developing a website with wallet feature. User can add any amount to their wallet, which can be used to play games or buy stuffs on the website. The site accepts cryptocurrency as their main payment.

ISSUE:
I am creating charges using "no_price" as pricing type. And when user pays using cryptocurrency, the completed screen shows "Thank you for your donation". I cannot find how to update this text while creating charges.
Please help!!

**Comment by antimech** [comment]
Currently the API doesn't allow to overwrite the behavior. Please refer your future questions to the Coinbase Commerce support: support@coinbase.com

**Comment by oa-coinbase** [comment]
Hi @responsivesudip yes setting a charge to "no_price" instead of "fixed_price" will trigger the donation flow. You should be able to ask for a charge amount from the user before making the create charge request. Let me know if I'm misunderstanding your use case.

**Comment by oa-coinbase** [comment]
I’m closing this issue because it has been inactive for a few months (granted, maintainers for this repo were in flux for a while). Please feel free to reopen it if you still encounter this issue with the latest stable version, thanks!
