### ISSUE TITLE
which method do i use to create a payment method

### ISSUE THREAD

**Issue by worldtok** [coinbase/coinbase-commerce-php#14]
I have tested the checkout and charge classes and none of them redirects a user to the payment gateway with the fixed price I have specified.
 
My question is how do I pass parameters to the user so that those parameters will be used as the payment amount without needing the user to enter another amount. 

And again I'm not being redirected to the payment gateway. Please tell me the method that will take me to the payment gateway.

**Comment by oa-coinbase** [comment]
@worldtok sorry for the massive delay; to answer your questions:
1. To establish a fixed price on behalf of the user, set the `pricing_type` to `fixed_price` and specify your price with `local_price`.
2. To send a user to your payment gateway, add a `redirect_url` (and/or `cancel_url`) when creating a customer Charge.

**Comment by oa-coinbase** [comment]
Hi @worldtok I’m closing this issue because it has been inactive for a while, but please feel free to reopen it if you still encounter this issue or would like help addressing it, thanks!
