### ISSUE TITLE
Unable to create charge : implode(): Passing glue string after array is deprecated. Swap the parameters

### ISSUE THREAD

**Issue by vishalinfyom** [coinbase/coinbase-commerce-php#16]
PHP Version : 7.0.4
OS: Win 10

Getting `Unable to create charge : implode(): Passing glue string after array is deprecated. Swap the parameters` error while trying to create charge.

**Comment by oa-coinbase** [comment]
Fixed in https://github.com/coinbase/coinbase-commerce-php/pull/18
