### ISSUE TITLE
Completely Broken Extension and No Support

### ISSUE THREAD

**Issue by perfpcs** [coinbase/coinbase-commerce-php#19]
What is the point of posting this extension when it does not even work with the latest Magento?? Currently all these issues exist with 2.3.4:

1. Cant view any orders made with extension:
1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Unable to find coinbase order with store id "ORD-200325-4-008"

2. Extension creates order immediately when submitting even if you change your mind and cancel or try to go back and return to checkout or cart.

3. Orders never complete sucessfully going to the success "thank you page" instead you always get:
"Sorry something went wrong, you will be redirected to checkout in 5 seconds." then back to checkout page...yet the order is made!

4. Numerous issues trying to cancel, view receipt, etc. Virtually anything you can click on with this extension is broke.

What is wrong with the developers that are in charge of this mess? No one replies to messages, I tried contact through Linkedin. I've sent 5 emails to Coinbbase Commerce Support and they never reply. I don't understand why have this extension and git page if no one responsible ever replies, tries to fix the extension or even shows up here. It's extremely frustrating and maddening because the extension actually looks visually nice and if it worked would be wonderful. Compared to the Coinpayments terrible extension this one actually is very customer friendly......to bad it is completely broken though. Does anyone have any idea how we can get help to fix this?

**Comment by oa-coinbase** [comment]
Hi @perfpcs sorry for the massive delays, we've shifted some priorities and I'll be taking a look at this repository this week.

**Comment by perfpcs** [comment]
Hi..it sure would be nice, I already had to spend my own money on upwork to fix the main problem which is unable to view coinbase orders in Admin. See all my posts here:
https://github.com/coinbase/coinbase-commerce-magento/issues

**Comment by omidahourai** [comment]
I’m closing this issue because we've decided to drop support for Magento at this time. It seems your issue has been inactive for a while now. However, please feel free to reopen it if you still encounter this issue with the latest stable version, or submit a PR if you've managed to fix it. Thanks!

**Comment by oa-coinbase** [comment]
I’m closing this issue because we've decided to drop support for Magento at this time. It seems your issue has been inactive for a while now. However, please feel free to reopen it if you still encounter this issue with the latest stable version, or submit a PR if you've managed to fix it. Thanks!
