### ISSUE TITLE
Can't install because old dependency guzzlehttp 5.x

### ISSUE THREAD

**Issue by spacie2136** [coinbase/coinbase-commerce-php#2]
Can you please update the Guzzlehttp version to 6^ ?
On my system:

google/apiclient                        v2.2.2  requires  guzzlehttp/guzzle (~5.3.1|~6.0)  
google/auth                             v1.3.3  requires  guzzlehttp/guzzle (~5.3.1|~6.0)  
rapidwebltd/php-google-oauth-2-handler  v1.2.2  requires  guzzlehttp/guzzle (^6.3)         

Error installing:

  Problem 1
    - Installation request for coinbase/coinbase-commerce ^1.0 -> satisfiable by coinbase/coinbase-commerce[v1.0.0].
    - Conclusion: remove guzzlehttp/guzzle 6.3.3
    - Conclusion: don't install guzzlehttp/guzzle 6.3.3
    - coinbase/coinbase-commerce v1.0.0 requires guzzlehttp/guzzle ^5.0 -> satisfiable by guzzlehttp/guzzle[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0, 5.2.0, 5.3.0, 5.3.1, 5.3.2, 5.3.3].
    - Can only install one of: guzzlehttp/guzzle[5.3.1, 6.3.3].
    - Can only install one of: guzzlehttp/guzzle[5.3.2, 6.3.3].
    - Can only install one of: guzzlehttp/guzzle[5.3.3, 6.3.3].
    - Can only install one of: guzzlehttp/guzzle[5.0.0, 6.3.3].
    - Can only install one of: guzzlehttp/guzzle[5.0.1, 6.3.3].
    - Can only install one of: guzzlehttp/guzzle[5.0.2, 6.3.3].
    - Can only install one of: guzzlehttp/guzzle[5.0.3, 6.3.3].
    - Can only install one of: guzzlehttp/guzzle[5.1.0, 6.3.3].
    - Can only install one of: guzzlehttp/guzzle[5.2.0, 6.3.3].
    - Can only install one of: guzzlehttp/guzzle[5.3.0, 6.3.3].
    - Installation request for guzzlehttp/guzzle (locked at 6.3.3) -> satisfiable by guzzlehttp/guzzle[6.3.3].

**Comment by asiop** [comment]
Same here

**Comment by guacamoli** [comment]
@spacie2136 @asiop, updated the guzzlehttp version.
