### ISSUE TITLE
Required parameter missing: pricing_type

### ISSUE THREAD

**Issue by arifnurdiansyah92** [coinbase/coinbase-commerce-php#22]
I tried to create charge

```
ApiClient::init(CryptoAPI::first()->apikey);
        $chargeObj = new Charge();

        $chargeObj->name = 'The Sovereign Individual';
        $chargeObj->description = 'Mastering the Transition to the Information Age';
        $chargeObj->local_price = [
            'amount' => '100.00',
            'currency' => 'USD'
        ];
        $chargeObj->pricing_type = 'fixed_price';
        $chargeObj->save();
        return redirect($chargeObj->hosted_url);
```

And got error `Required parameter missing: pricing_type`

PHP 7.2
Shared Hosting

**Comment by oa-coinbase** [comment]
Hey @arifnurdiansyah92 I just tried your code with my own API key, seemed to work fine. Are you still having this issue?

**Comment by oa-coinbase** [comment]
I’m closing this issue because it has been inactive for a while now. However, please feel free to reopen it if you still encounter this issue with the latest stable version, or please submit a PR if you've managed to fix it. Thanks!
