### ISSUE TITLE
Error: Internal Server Error, Code: 500

### ISSUE THREAD

**Issue by jigs1996** [coinbase/coinbase-commerce-php#25]
**Request**
```POST https://api.commerce.coinbase.com/charges```

**Headers:**
```
Content-Type:application/json
X-CC-Api-Key:*****************************
X-CC-Version:2018-03-22

```
**Body:**
```
name:test
description:test
pricing_type:fixed_price
local_price[amount]:100
local_price[currency]:USD
```

**Response**
```
{
    "status": 500,
    "error": "Internal Server Error"
}
```

**Comment by oa-coinbase** [comment]
@jigs1996 don't see anything wrong with your code, this works fine for me. Can you double check?
```
curl https://api.commerce.coinbase.com/charges \
     -X POST \
     -H 'Content-Type: application/json' \
     -H "X-CC-Api-Key: <YOUR_API_KEY>" \
     -H "X-CC-Version: 2018-03-22" \
     -d '{
       "name": "test",
       "description": "test",
       "local_price": {
         "amount": "100",
         "currency": "USD"
       },
       "pricing_type": "fixed_price"
     }'
```

**Comment by jigs1996** [comment]
![Screenshot (140)](https://user-images.githubusercontent.com/28808327/81033602-d315d380-8eb1-11ea-95c6-feae66e7967c.png)

I have send a request via curl, as you have given with my API Key but still the same error.

**Comment by jigs1996** [comment]
It's working now.
We have used other coinbase account which has all completed steps. i mean added wallet and auth and etc ...

But rather than getting 500: internal server error, I think your API should give us a proper message so we know what's missing. in an earlier account we haven't completed the wallet setup.
