### ISSUE TITLE
How to check for overpaid?

### ISSUE THREAD

**Issue by Fossil01** [coinbase/coinbase-commerce-php#26]
The API docs leave me puzzled how I should check for overpaid (or underpaid) payments.

Currently my webhook is checking for:

```php
if ($event->type == 'charge:confirmed' || $event->type == 'charge:resolved') {
```

**Comment by omidahourai** [comment]
Hi @Fossil01, unfortunately the current api does not support under/overpaid for webhooks. Do you have a specific reason or use case, maybe it would help me understand the need more clearly.

**Comment by oa-coinbase** [comment]
Hi @Fossil01, unfortunately the current api does not support under/overpaid for webhooks. Do you have a specific reason or use case, maybe it would help me understand the need more clearly.

**Comment by oa-coinbase** [comment]
@Fossil01 oops, correction - under/overpaid will appear on the `charge:failed` event, within the timeline context. Sorry for the confusion, if you have a follow-up question feel free to open another ticket, will close this one out now.
