### ISSUE TITLE
How to get BTC only payments?

### ISSUE THREAD

**Issue by antimech** [coinbase/coinbase-commerce-php#3]
Hello. I want to make only BTC payments available, without local currency, without other crypto currencies. How can I get that?

Thanks!

**Comment by guacamoli** [comment]
Hey @antimech, you can toggle specific currencies off by logging into your Coinbase Commerce Dashboard and going to the Settings page.

<img width="1511" alt="screen shot 2018-12-19 at 11 33 40 am" src="https://user-images.githubusercontent.com/89000/50243431-0d94d400-0382-11e9-9485-bdb33e3970ac.png">

**Comment by antimech** [comment]
No! I mean BTC only, not local USD equivalent!

**Comment by antimech** [comment]
@grahamjenson open this issue.
