### ISSUE TITLE
Verify SSL removed?

### ISSUE THREAD

**Issue by 0xGREG** [coinbase/coinbase-commerce-php#33]
Did you remove the verify SSL option? I wanna test stuff on local server and I can't because the verify ssl option is removed...

**Comment by renatofrota** [comment]
It's just not added to an official release yet (latest is 1.0.11 and miss this function).

If you are installing via Composer, import specifically **dev-master** version to have latest code.

If you have installed whatever other way, download this repository and extract over your install or just do [these changes](https://github.com/coinbase/coinbase-commerce-php/commit/76f9fad1a4ef33eef6fabee64f2c01171edda998) manually.
