### ISSUE TITLE
Send money to someone

### ISSUE THREAD

**Issue by Asmitta-01** [coinbase/coinbase-commerce-php#38]
Please how can we send money to a customer with this APi ? I have no ideas yet but i want to add this function to my website

**Comment by bcdbuddy** [comment]
Hey @Asmitta-01 

Have a look at this 
![image](https://user-images.githubusercontent.com/17571380/115492030-89540380-a250-11eb-825a-45fee07cecfa.png)

https://commerce.coinbase.com/docs/api/#resolve-a-charge

**Comment by Asmitta-01** [comment]
http request are not easy for me, I don't know where to write this code.
But thanks
