### ISSUE TITLE
Sandbox or sending test webhooks?

### ISSUE THREAD

**Issue by zerocarbthirty** [coinbase/coinbase-commerce-php#46]
Hi,

I have been working with PayPal's API for almost 10 years. One thing they do that I can't find on your system is sandboxing. I also can't figure out any way to send test webhook events. Can you guys please advise?

**Comment by zerocarbthirty** [comment]
Also where does the API redirect the user to after they make a payment? How do you set the redirect url in the charge?

**Comment by sahil-cb** [comment]
Hey there - you can find webhook documentation [here](https://commerce.coinbase.com/docs/api/#webhooks). When you set up webhooks from settings, you can also fire test webhooks from the UI.

There is a redirect_url param when creating a charge. See [API docs](https://commerce.coinbase.com/docs/api/#create-a-charge) for reference. If you're using our hosted checkouts, the page will automatically redirect to the appropriate redirect url after payment is completed.

Hope this helps.
