### ISSUE TITLE
Sandbox mode?

### ISSUE THREAD

**Issue by sjelfull** [coinbase/coinbase-commerce-php#7]
How do you make test payments?

**Comment by dev-variety** [comment]
I would like to know this too.

**Comment by jcgdjob** [comment]
https://support.coinbase.com/customer/en/portal/articles/2648039-do-you-have-a-sandbox-for-testing-how-do-you-recommend-testing-my-integration-?b_id=13521

No sandbox according to Coinbase.

**Comment by baranovserhiy** [comment]
As I understand we have to test the ecomerce API with real transactions?

**Comment by sjelfull** [comment]
@baranovserhiy Correct. As far as I can tell there is no testnet option.

**Comment by sjelfull** [comment]
@joshuachinemezu @maksim-s @guacamoli @imeleshko What is your official policy on support/PRs here?

And particularly this question is important, and should be covered in your FAQ.

**Comment by oa-coinbase** [comment]
@sjelfull @baranovserhiy sorry for the massive delay, I'll be taking a look at this repo this week.

**Comment by oa-coinbase** [comment]
I’m closing this issue because it has been inactive for a few months (granted, maintainers for this repo were in flux for a while). Please feel free to reopen it if you still have something to report or issues around testing in production, thanks!

**Comment by gabrielmcv** [comment]
There is any note regards this?

**Comment by nobodyw** [comment]
Sandbox mode always off for the php api?

**Comment by IvoPereira** [comment]
@oa-coinbase was there any update on the testnet for Coinbase Commerce?

I am pinging in this as you have mentioned there might be some news at the end of the previous year, 2020.

**Comment by mrkeyiano** [comment]
> @oa-coinbase was there any update on the testnet for Coinbase Commerce?
> 
> I am pinging in this as you have mentioned there might be some news at the end of the previous year, 2020.

@oa-coinbase any update? its 2022

**Comment by x011** [comment]
> > @oa-coinbase was there any update on the testnet for Coinbase Commerce?
> > I am pinging in this as you have mentioned there might be some news at the end of the previous year, 2020.
> 
> @oa-coinbase any update? its 2022

I'm sure 2050 will come and nothing has changed, remember, it's coinbase...

**Comment by GoekhanDev** [comment]
Really disappointing.

**Comment by moccajoghurt** [comment]
I can't test my code, moving to another service.

**Comment by exwyezed** [comment]
> If you've built a custom integration using our API, there are a couple ways to test your integration. To test that your service responds to webhook notifications appropriately, you can send test webhooks by visiting the [settings page](https://beta.commerce.coinbase.com/settings/notifications), scrolling down to the Webhook subscriptions section, clicking on Details next to the relevant webhook, and clicking the Send test button. Additionally, we recommend making a small purchase from your store to ensure that the end-to-end integration is working correctly.
>
> At this time, we don't offer any test or sandbox accounts, but it's something that we’re hoping to provide in the future.

### List of webhook events
**charge:confirmed
charge:created
charge:delayed
charge:failed
charge:pending
charge:resolved
invoice:created
invoice:paid
invoice:payment_pending
invoice:unresolved
invoice:viewed
invoice:voided**

I hope it helps. It helped me. Invoice API docs are incomplete.
