### ISSUE TITLE
Error occured. Invalid payload provided. No JSON object could be decoded.

### ISSUE THREAD

**Issue by adam-gweleg** [coinbase/coinbase-commerce-php#9]
Please help me to fix this issue in the webhook.php

**Comment by oa-coinbase** [comment]
Hi @adam-gweleg can you provide some more context on your issue? Are you following the instructions in [examples/Webhook/README.md](https://github.com/coinbase/coinbase-commerce-php/blob/master/examples/Webhook/README.md)? I've updated it to mention the shared secret you must copy/paste into the example code.

**Comment by oa-coinbase** [comment]
I’m closing this issue because it has been inactive for a while now. However, please feel free to reopen it if you still encounter this issue with the latest stable version, or please submit a PR if you've managed to fix it. Thanks!

**Comment by MrlolGFX** [comment]
help please I have the same problem in node js and I can't solve it

**Comment by MrlolGFX** [comment]
`app.post('/pay/crypto/charge', rate, async (req, res) => {
  const webhookSecret = 'my-secret';
  var event;

	console.log(req.headers);

	try {
		event = Webhook.verifyEventBody(
			req.rawBody,
			req.headers['x-cc-webhook-signature'],
			webhookSecret
		);
    console.log(event);
	} catch (error) {
		console.log('Error occured', error.message);

		return res.status(400).send('Webhook Error:' + error.message);
	}
})`
